# Generated by Django 3.2 on 2021-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=10, default=5555, max_digits=19),
            preserve_default=False,
        ),
    ]
