# Generated by Django 3.2 on 2021-04-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='fiyat',
            field=models.DecimalField(decimal_places=10, default=2222, max_digits=19),
            preserve_default=False,
        ),
    ]
