# Generated by Django 3.2 on 2021-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210423_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fiyat',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
    ]
