# Generated by Django 3.2 on 2021-05-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Kabul Edildi'), ('Preaparing', 'Hazırlanıyor'), ('OnShipping', 'Kargo'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='New', max_length=10),
        ),
    ]
